Upgrade
nymlab/AVIDA pull request #19
Opened 2024-12-31 11:30 UTC by iorveth

Closes https://github.com/nymlab/AVIDA/issues/16

2025-01-01 12:56 UTC, whalelephant requested changes
Thank you for this! some organisation comments for your feedback!

2025-01-01 12:56 UTC, whalelephant commented on contracts/sdjwt-verifier/src/errors.rs
> +impl std::fmt::Display for SdjwtVerifierResultError {
why impl and not just instead of using `thiserror::Error`?

2025-01-01 12:56 UTC, whalelephant commented on packages/common/src/traits.rs
do we need this file? this is basically the expected `ExecMsg` right?

2025-01-01 12:56 UTC, whalelephant commented on contracts/sdjwt-verifier/src/msg.rs
> +pub enum ExecuteMsg {
these can be moved to the package so to act as "interface". 

Please look at https://github.com/CosmWasm/cw-plus/tree/main/packages/cw20 and how the packages are used in the contract implementations.

2025-01-01 12:56 UTC, whalelephant commented on contracts/sdjwt-verifier/Cargo.toml
> +serde-json-wasm = {workspace = true}
I saw this 
https://github.com/CosmWasm/cosmwasm/issues/2195

looks like we can replace  remove it?

2025-01-01 12:56 UTC, whalelephant commented on contracts/sdjwt-verifier/src/state.rs
> +pub const MAX_PRESENTATION_LENGTH: Item<usize> = Item::new("max_presentation_length");
I would say some of these states can be moved to the package to be shared across verifier implementations.

For example, we have the type`VerfiablePresentation` as `Binary` in the package because it will be required for any verifier, sd-jwt, anoncreds, zk, etc.

2025-01-02 13:23 UTC, iorveth commented on packages/common/src/traits.rs
https://github.com/nymlab/AVIDA/pull/19/commits/9d623bbf40b832903712b27cc56cecb010e74a09

2025-01-02 13:51 UTC, iorveth commented on contracts/sdjwt-verifier/src/msg.rs
> +pub enum ExecuteMsg {
Good point, done https://github.com/nymlab/AVIDA/pull/19/commits/19c8202f0ff87688379c9a4b56fb01451014e6ed

2025-01-02 14:00 UTC, iorveth commented on contracts/sdjwt-verifier/Cargo.toml
> +serde-json-wasm = {workspace = true}
Sure, https://github.com/nymlab/AVIDA/pull/19/commits/f8166566cf2d12d924bbb4ea62706a29019518c5

2025-01-02 14:23 UTC, iorveth commented on contracts/sdjwt-verifier/src/state.rs
> +pub const MAX_PRESENTATION_LENGTH: Item<usize> = Item::new("max_presentation_length");
Moved `MAX_PRESENTATION_LENGTH` to package, let's see what we can reuse after we develop other verifiers.
https://github.com/nymlab/AVIDA/pull/19/commits/52c864a9ccac2de41aebf1787b66cf7008502adc

2025-01-02 14:23 UTC, iorveth commented on contracts/sdjwt-verifier/src/errors.rs
> +impl std::fmt::Display for SdjwtVerifierResultError {
Done https://github.com/nymlab/AVIDA/pull/19/commits/52c864a9ccac2de41aebf1787b66cf7008502adc

2025-01-18 12:55 UTC, whalelephant requested changes

2025-01-18 12:55 UTC, whalelephant commented on scripts/build.sh
> -for file in ./artifacts/*; do
lets keep this for arch builds

2025-01-18 13:10 UTC, whalelephant commented on scripts/build.sh
> -for file in ./artifacts/*; do
sorry this is no longer needed

2025-01-18 13:10 UTC, whalelephant approved these changes
great job!

2025-01-18 13:11 UTC, merged